const actionTypes = {
    GET_EXISTING_COMPETITIONS: 'GET_EXISTING_COMPETITIONS',
    GET_EXISTING_COMPETITIONS_SUCCESS: 'GET_EXISTING_COMPETITIONS_SUCCESS',
    GET_EXISTING_COMPETITIONS_FAILURE: 'GET_EXISTING_COMPETITIONS_FAILURE',
}

export default actionTypes