const actionTypes = {
    GET_EXISTING_COMPETITIONS: 'GET_EXISTING_COMPETITIONS',
    GET_EXISTING_COMPETITIONS_SUCCESS: 'GET_EXISTING_COMPETITIONS_SUCCESS',
    GET_EXISTING_COMPETITIONS_FAILURE: 'GET_EXISTING_COMPETITIONS_FAILURE',
    CREATE_NEW_COMPETITION: 'CREATE_NEW_COMPETITION',
    CREATE_NEW_COMPETITION_SUCCESS: 'CREATE_NEW_COMPETITION_SUCCESS',
    CREATE_NEW_COMPETITION_FAILURE: 'CREATE_NEW_COMPETITION_FAILURE',
    CREATE_NEW_TEAM: 'CREATE_NEW_TEAM',
    CREATE_NEW_TEAM_SUCCESS: 'CREATE_NEW_TEAM_SUCCESS',
    CREATE_NEW_TEAM_FAILURE: 'CREATE_NEW_TEAM_FAILURE',
    CREATE_NEW_ATHLETE: 'CREATE_NEW_ATHLETE',
    CREATE_NEW_ATHLETE_SUCCESS: 'CREATE_NEW_ATHLETE_SUCCESS',
    CREATE_NEW_ATHLETE_FAILURE: 'CREATE_NEW_ATHLETE_FAILURE',
}

export default actionTypes