export const GET_EXISTING_COMPETITIONS = 'GET_EXISTING_COMPETITIONS';
export const GET_EXISTING_COMPETITIONS_SUCCESS = 'GET_EXISTING_COMPETITIONS_SUCCESS';
export const GET_EXISTING_COMPETITIONS_FAILURE = 'GET_EXISTING_COMPETITIONS_FAILURE';